### ISSUE TITLE
Feature request : Kube Labels -> Consul Tags sync

### ISSUE THREAD

**Issue by BarthV** [cloudwatt/kube2consul#4]
Hi !

Since Annotations are not available in Endpoints metadata, I suggest using only label for this case.
This is 2 kinds of possible consul tags : 
* single tags : `mytag` `secondtag` ...
* map tags : `foo=bar` `cluster=acme`  ...

kube2consul should support both :)

I made a very quick-and-dirty working proof of concept here : https://github.com/BarthV/kube2consul/tree/using-labels

This is what I'm thinking about : 
```
apiVersion: v1
kind: Service
metadata:
  name: my-service-01
  namespace: myservices
  labels:
    k2c-singletags: mytag_secondtag
    foo: bar
    cluster: acme
spec:
[...]
```
_It's also possible to add a "flag" label that would enable/disable this feature to optimize perfs_

Thanks !
