### ISSUE TITLE
Feature request : allow prefixing and overriding Consul service-name

### ISSUE THREAD

**Issue by BarthV** [cloudwatt/kube2consul#5]
Hi !

It should be possible to ask kube2consul to dynamicly change the target service name in Consul based on Endpoint metadata. Since Annotations are not available in Endpoints metadata, I suggest using only label for this case.

This is what I'm thinking about :
```
apiVersion: v1
kind: Service
metadata:
  name: my-service-02
  namespace: myservices
  labels:
    k2c-servicename: 'my-svc-two-in-consul'
    k2c-serviceprefix: 'foobar-'
spec:
[...]
```
_Obviously, `k2c-servicename` wins if both are specified._

Thanks !
